TRANSFORMING_ROTATION_RANGE = (-45, 45)
TRANSFORMING_TRANSLATION_RATIO_RANGE = (-0.1, 0.1)
TRANSFORMING_SCALE_RATIO_RANGE = (0.9, 1.2)
COLOR_SCALE_RATIO_RANGE = (0.6, 1.4)
COLOR_JITTER_BRIGHTNESS_RANGE = (0.6, 1.4)
COLOR_JITTER_CONTRAST_RANGE = (0.6, 1.4)
COLOR_JITTER_SATURATION_RANGE = (0.6, 1.4)
COLOR_JITTER_GAMMA_RANGE = (0.6, 1.4)

RANDOM_ERASING_PERFORM_RATIO = 0.5
RANDOM_ERASING_AREA_RATIO_RANGE = (0.02, 0.2)
RANDOM_ERASING_ASPECT_RATIO_RANGE = (0.3, 1/0.3)
RANDOM_ERASING_AREA_VALUE_RANGE = (0, 1)
RANDOM_ERASING_PIXEL_LEVEL = False
RANDOM_ERASING_GRAY_AREA = False

COLOR_JITTER_BRIGHTNESS_PERFORM = False
COLOR_JITTER_CONTRAST_PERFORM = False
COLOR_JITTER_SATURATION_PERFORM = False
COLOR_JITTER_GAMMA_PERFORM = False